"""
Django settings for ThucHanh project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    """Đọc file .env (KEY=value) vào os.environ nếu chưa có biến hệ thống."""
    path = BASE_DIR / '.env'
    if not path.is_file():
        return
    try:
        for raw in path.read_text(encoding='utf-8').splitlines():
            line = raw.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            key, _, val = line.partition('=')
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val
    except OSError:
        pass


_load_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fw3_4op7buf@pi9929%i6o*jo=)j$#^1irn3(7+nxba-b_q3s*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

# Stripe API Keys
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY', 'pk_test_51TFGfSCTdSc4o7mItbuOp5I2xFLdwcBmYJTw5NRhJGIW7mOTT7sfKFyksZzbPwwYLdsKAv5cRebCc5zO15btNVUb00tqQ2ZlSs') 
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', 'sk_test_51TFGfSCTdSc4o7mIsXH9jw2VIM2jqf38V6LdVaQ8MAZR23FhFoiChvT7GziwY5pWBWAreInWyChnhVwvDGGPdnbG00Sz6jVgwr')


OSGEO4W = r'E:\OSGEO4W'
os.environ['OSGEO4W_ROOT'] = OSGEO4W
os.environ['GDAL_DATA'] = os.path.join(OSGEO4W, 'share', 'gdal')
os.environ['PROJ_LIB'] = os.path.join(OSGEO4W, 'share', 'proj')
os.environ['PATH'] = os.path.join(OSGEO4W, 'bin') + ';' + os.environ['PATH']

GDAL_LIBRARY_PATH = os.path.join(OSGEO4W, 'bin', 'gdal312.dll')
GEOS_LIBRARY_PATH = os.path.join(OSGEO4W, 'bin', 'geos_c.dll')

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'ThucHanhApp',
]

# Mailtrap API (django-anymail): bật nếu có MAILTRAP_API_TOKEN và đã pip install django-anymail
MAILTRAP_API_TOKEN = os.environ.get('MAILTRAP_API_TOKEN', '').strip()
_HAS_ANYMAIL = importlib.util.find_spec('anymail') is not None
if MAILTRAP_API_TOKEN and _HAS_ANYMAIL:
    INSTALLED_APPS = list(INSTALLED_APPS) + ['anymail']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ThucHanh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ThucHanh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'quan_ly_cua_hang_tien_loi',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'ThucHanhApp' / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Email — Mailtrap Sandbox
# - Có MAILTRAP_API_TOKEN + django-anymail → gửi qua Mailtrap API (sandbox).
# - Ngược lại → SMTP sandbox (sandbox.smtp.mailtrap.io).
# File .env (đã gitignore): xem .env.example
# ---------------------------------------------------------------------------
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'WebGIS Cửa Hàng <no-reply@example.com>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

if MAILTRAP_API_TOKEN and _HAS_ANYMAIL:
    EMAIL_BACKEND = 'anymail.backends.mailtrap.EmailBackend'
    ANYMAIL = {'MAILTRAP_API_TOKEN': MAILTRAP_API_TOKEN}
    _mt_sid = os.environ.get('MAILTRAP_SANDBOX_ID', '').strip()
    if _mt_sid.isdigit():
        ANYMAIL['MAILTRAP_SANDBOX_ID'] = int(_mt_sid)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'sandbox.smtp.mailtrap.io')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '2525'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes', 'on')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    # DEBUG mà chưa có SMTP user/pass → in ra console
    if DEBUG and not (EMAIL_HOST_USER and EMAIL_HOST_PASSWORD):
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

