# Generated by Django 6.0.1 on 2026-02-05 12:16

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cua_hang', models.CharField(max_length=200)),
                ('dia_chi', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
                'db_table': 'cua_hang',
            },
        ),
        migrations.CreateModel(
            name='LoaiCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loại cửa hàng',
                'verbose_name_plural': 'Loại cửa hàng',
                'db_table': 'loai_cua_hang',
            },
        ),
        migrations.CreateModel(
            name='SuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_su_kien', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Sự kiện',
                'db_table': 'su_kien',
                'ordering': ['-ngay_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nhan_xet', models.TextField(blank=True)),
                ('ngay_danh_gia', models.DateField()),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='ThucHanhApp.cuahang')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'danh_gia',
                'ordering': ['-ngay_danh_gia'],
            },
        ),
        migrations.AddField(
            model_name='cuahang',
            name='loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cua_hangs', to='ThucHanhApp.loaicuahang'),
        ),
        migrations.CreateModel(
            name='CuaHangSuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su_kiens', to='ThucHanhApp.cuahang')),
                ('su_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cua_hangs', to='ThucHanhApp.sukien')),
            ],
            options={
                'verbose_name': 'Cửa hàng - Sự kiện',
                'verbose_name_plural': 'Cửa hàng - Sự kiện',
                'db_table': 'cua_hang_su_kien',
                'unique_together': {('cua_hang', 'su_kien')},
            },
        ),
    ]
