# Generated by Django 6.0.1 on 2026-03-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukien',
            name='la_hang_tuan',
            field=models.BooleanField(default=False, verbose_name='Sự kiện hàng tuần'),
        ),
        migrations.AddField(
            model_name='sukien',
            name='ngay_trong_tuan',
            field=models.IntegerField(blank=True, choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], null=True, verbose_name='Ngày trong tuần'),
        ),
    ]
