# Generated by Django 6.0.1 on 2026-03-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0002_sukien_la_hang_tuan_sukien_ngay_trong_tuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sukien',
            name='ngay_trong_tuan',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Ngày trong tuần'),
        ),
    ]
