# Generated by Django 6.0.1 on 2026-03-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0003_alter_sukien_ngay_trong_tuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mat_hang', models.CharField(max_length=200)),
                ('don_vi', models.CharField(default='cái', max_length=50)),
                ('gia_ban', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('mo_ta', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mặt hàng',
                'verbose_name_plural': 'Mặt hàng',
                'db_table': 'mat_hang',
                'ordering': ['ten_mat_hang'],
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_giao', 'Đang giao'), ('da_thanh_toan', 'Đã thanh toán'), ('da_huy', 'Đã hủy')], default='cho_xu_ly', max_length=20)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ghi_chu', models.TextField(blank=True)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hangs', to='ThucHanhApp.cuahang')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'don_hang',
                'ordering': ['-ngay_dat'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('thanh_tien', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='ThucHanhApp.donhang')),
                ('mat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThucHanhApp.mathang')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'chi_tiet_don_hang',
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='ThucHanhApp.cuahang')),
                ('mat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_khos', to='ThucHanhApp.mathang')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'db_table': 'ton_kho',
                'unique_together': {('cua_hang', 'mat_hang')},
            },
        ),
    ]
