# Generated by Django 6.0.1 on 2026-03-09 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0004_mathang_donhang_chitietdonhang_tonkho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='nguoi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_gias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donhang',
            name='nguoi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hangs', to=settings.AUTH_USER_MODEL),
        ),
    ]
