# Generated by Django 6.0.1 on 2026-04-15 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0009_adminthongbao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
                'db_table': 'gio_hang',
            },
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThucHanhApp.cuahang')),
                ('mat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThucHanhApp.mathang')),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='ThucHanhApp.giohang')),
            ],
            options={
                'verbose_name': 'Chi tiết giỏ hàng',
                'verbose_name_plural': 'Chi tiết giỏ hàng',
                'db_table': 'chi_tiet_gio_hang',
                'unique_together': {('gio_hang', 'cua_hang', 'mat_hang')},
            },
        ),
    ]
