# Generated by Django 6.0.1 on 2026-04-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0011_donhang_dia_chi_giao_hang_donhang_sdt_giao_hang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='cua_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ThucHanhApp.cuahang'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='cua_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_hangs', to='ThucHanhApp.cuahang'),
        ),
    ]
