# Generated by Django 6.0.1 on 2026-05-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0012_chitietdonhang_cua_hang_alter_donhang_cua_hang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='hanh_dong',
            field=models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('view', 'Xem'), ('import', 'Nhập dữ liệu'), ('export', 'Xuất dữ liệu'), ('other', 'Khác')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='LichSuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('nhap', 'Nhập kho'), ('xuat', 'Xuất kho'), ('cap_nhat', 'Cập nhật'), ('import', 'Nhập từ Excel')], default='cap_nhat', max_length=20)),
                ('so_luong_truoc', models.IntegerField(default=0)),
                ('so_luong_sau', models.IntegerField(default=0)),
                ('so_luong_thay_doi', models.IntegerField(default=0)),
                ('ghi_chu', models.TextField(blank=True)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thuc_hien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ton_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='ThucHanhApp.tonkho')),
            ],
            options={
                'verbose_name': 'Lịch sử kho',
                'verbose_name_plural': 'Lịch sử kho',
                'db_table': 'lich_su_kho',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
