# Generated by Django 6.0.1 on 2026-05-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThucHanhApp', '0013_alter_auditlog_hanh_dong_lichsukho'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'danh_muc',
                'ordering': ['ten_danh_muc'],
            },
        ),
        migrations.AddField(
            model_name='mathang',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mat_hangs', to='ThucHanhApp.danhmuc'),
        ),
    ]
